name: Bug report
description: Report bugs with the engine here
labels: ["Type: Bug","Awaits labels"]
body:
  - type: textarea
    id: description
    attributes:
      
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Terminal logs (latest.log)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "Are you modding a build from source or with Lua?"
      options:
        - Lua
        - Source
        - No modding
    validations:
      required: true  

  - type: input
    id: pslice-version
    attributes:
      label: "In which version of P-Slice this occurs in (if it's the build from the Actions tab, then also include the commit hash of the build)"
      placeholder: "3.2.1"
    validations:
      required: true

  - type: dropdown
    id: psych
    attributes:
      label: "Which \"Psych engine\" version of P-Slice this occurs in"
      options:
        - 0.6.3
        - 1.0.4
        - Both
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "Android"
        - "iOS"
        - "HTML5"
    validations:
      required: true
      

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: true
